name: Validate domains

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-for-duplicates:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Validate domains
      run: |
        invalid_domains=()
        tmpfile=$(mktemp)
        jq -r '.programs[].domains[]' chaos-bugbounty-list.json > "$tmpfile"
        while IFS= read -r tld; do
            if [[ "$tld" != $(echo "$tld" | awk -F . '{print $(NF-1)"."$NF}') ]]; then
            echo $tld >> invalid_domains.txt
            fi
        done < "$tmpfile"

        if [[ -s invalid_domains.txt ]]; then
            echo "Invalid domains found: $(cat invalid_domains.txt)"
            exit 1
        fi