name: Validate domains

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-for-duplicates:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup golang
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Installing Validate domains binary
      run: |
        go install github.com/projectdiscovery/public-bugbounty-programs/cmd/validate-domains
      shell: bash

    - name: Check domains validation
      run: |
        validate-domains -file chaos-bugbounty-list.json
      shell: bash

    - name: Return invalid if present
      run: |
        if [[ -s invalid_domains.txt ]]; then
            echo "Invalid domains found: $(cat invalid_domains.txt)"
            exit 1
        fi
